✨ NEW: add wallet api charts
modernlion/kkr-ops pull request #2
Opened 2023-03-08 08:43 UTC by mush8room

## 작업 내용

> 작업 내용에 대한 summary를 작성해주세요
- wallet api에 대한 helm chart 생성

## Merge 전 필요 작업

> Merge 되기 전에 필요한 작업이 있다면 작성해주세요

- N/A

## 관련 링크

> 작업하시면서 참고한 링크가 있거나 리뷰할 때 확인해야 하는 링크가 있다면 작성해주세요

- N/A

## 희망 리뷰 완료일

> 빨리 리뷰를 끝내고 merge 되어야 하는 작업이라면 리뷰 완료일을 작성해주세요

- N/A

## 기타 사항

> 그 외 기타 사항이 있다면 작성해주세요

- mumbai namespace에 배포 후 app 쪽에 noti 필요

2023-03-09 15:34 UTC, changpyo-modernlion commented on charts/kkr/wallet-api/templates/ingress/kongplugin.yaml
> +{{- $validateAuthServerTokenPluginName := printf "%s-%s" $fullName "validate-auth-server-token" }}
플러그인 name을 지정하는 코드 스타일로 _helpers를 활용하는 것으로 통일해보고 있습니다.
이런 [PR](https://github.com/likelion-campus/mkp-ops/pull/50) 참조해서 수정해봤으면 좋겠습니다.

2023-03-09 15:46 UTC, changpyo-modernlion approved these changes
리뷰하다보니 chart 스타일이 제각각이어서 통일이 필요할 것 같습니다.
아직 문서로 만들어지진 않아서 가이드 합의가 되면 한번에 수정하는게 좋겠습니다.
deployment에서 값을 부르는거나 ingress가 안될 이슈는 없을 것으로 판단됩니다.
private ingress에 /private 라우팅이 없어서 한번 더 PR진행될 것으로 예상됩니다.
고생하셨습니다.

2023-03-10 03:24 UTC, mush8room commented on charts/kkr/wallet-api/templates/ingress/kongplugin.yaml
> +{{- $validateAuthServerTokenPluginName := printf "%s-%s" $fullName "validate-auth-server-token" }}
말씀하신 PR 참조해서 반영해두었습니다.
적절히 되었는지 한 번 체크 부탁드리겠습니다!

2023-03-10 03:25 UTC, mush8room commented
wallet api 쪽에 아직 public / private 분리가 이루어지지 않아서 해당 부분은  endpoint 분리 작업 이루어진 후 별도 PR 올리도록 하겠습니다.

2023-03-11 06:55 UTC, boksil-lion requested changes
@changpyo-modernlion 님의 의견 주신 것처럼 중복되는 리소스네이밍 등을 `_helper.tpl` 에 놓고 공용으로 사용하는 것도 좋을 것 같습니다.

2023-03-11 06:55 UTC, boksil-lion commented on charts/kkr/wallet-api/templates/ingress/ingress.api.private.yaml
> +    konghq.com/plugins: {{ $fullName }}-cors,{{ $fullName }}-validate-auth-server-token
```suggestion
    konghq.com/plugins: {{ include "wallet-api.corsPluginName" . }},{{ include "wallet-api.validateAuthServerTokenPluginName" . }}
```
`_helper` 에 적용한 내용을 반영하려면, 이 부분에 함께 적용되야 맞을 것 같습니다. (그리고 이에 맞게 `_helper.tpl` 이 업데이트되어야 합니다. 이 부분은 추가로 가이드 해드리겠습니다.)

2023-03-11 06:58 UTC, mush8room commented on charts/kkr/wallet-api/templates/ingress/ingress.api.private.yaml
> +    konghq.com/plugins: {{ $fullName }}-cors,{{ $fullName }}-validate-auth-server-token
네 해당 부분 `_helper.tpl`로 분리하였다가  argocd에서 sync error가 발생하여서 일단 revert 해두었습니다.
tx 관련 이슈가 발생했는데 연관되어 있는 부분인가 싶어서  revert 했는데, 아닌 것으로 파악되어서 다시 적용한 상태 올려두도록 하겠습니댜.

2023-03-16 10:49 UTC, merged