:zap: UPDATE: auth charts
modernlion/kkr-ops pull request #3
Opened 2023-03-10 02:37 UTC by mush8room

## 작업 내용

> 작업 내용에 대한 summary를 작성해주세요
- auth 쪽 업데이트 되지 않은 env들 추가
- configMap으로 몰려있던 정보들 secret과 configMap으로 분리

## Merge 전 필요 작업

> Merge 되기 전에 필요한 작업이 있다면 작성해주세요

- N/A

## 관련 링크

> 작업하시면서 참고한 링크가 있거나 리뷰할 때 확인해야 하는 링크가 있다면 작성해주세요

- N/A

## 희망 리뷰 완료일

> 빨리 리뷰를 끝내고 merge 되어야 하는 작업이라면 리뷰 완료일을 작성해주세요

- N/A

## 기타 사항

> 그 외 기타 사항이 있다면 작성해주세요

- N/A

2023-03-10 04:33 UTC, mush8room commented
mumbai 쪽에 배포할 때는 아예 app을 새로 배포하면 될 것 같습니다

2023-03-11 06:41 UTC, boksil-lion requested changes
여기에, 지갑 생성 이벤트 SQS 를 처리하는 worker deployment 도 함께 포함하고, chart 의 설정에서 처리할 수 있도록 하면 좋을 것 같습니다.
`values.yaml` 에서 `worker.enable = true / false` 로 해당 deployment 배포할 수 있으면 좋겠어요.

2023-03-11 08:33 UTC, mush8room commented
지갑 생성 이벤트 처리 deployment를 별도 chart로 만드는 것과 하나의 chart로 관리하는 것 중에 어느 쪽이 더 좋은 방안일까요??

2023-03-14 07:04 UTC, boksil-lion commented
worker deployment 는 추가로 차트 수정을 통해 배포하는 것으로 결정하였습니다.

2023-03-14 07:04 UTC, merged