✨ UPDATE: seperate igress
modernlion/kkr-ops pull request #4
Opened 2023-03-14 02:44 UTC by mush8room

## 작업 내용

> 작업 내용에 대한 summary를 작성해주세요
- private과 public endpoint 분리에 따른 ingress 분리
- PR #2 과 연관되어 있어서 [⚡ UPDATE: seperate public/private ingress](https://github.com/modernlion/kkr-ops/commit/feb23a2907daaff4e9a3d57e03c62d7771495845) 부터 확인해주시면 됩니다.

## Merge 전 필요 작업

> Merge 되기 전에 필요한 작업이 있다면 작성해주세요

- [kkr-wallet PR #39](https://github.com/modernlion/kkr-wallet-api/pull/39)과 함께 반영되어야 합니다.

## 관련 링크

> 작업하시면서 참고한 링크가 있거나 리뷰할 때 확인해야 하는 링크가 있다면 작성해주세요

- N/A

## 희망 리뷰 완료일

> 빨리 리뷰를 끝내고 merge 되어야 하는 작업이라면 리뷰 완료일을 작성해주세요

- N/A

## 기타 사항

> 그 외 기타 사항이 있다면 작성해주세요

- N/A

2023-03-14 02:45 UTC, mush8room commented on charts/kkr/wallet-api/templates/ingress/ingress.api.public.yaml
> +    {{- toYaml . | nindent 4 }}
public은 kong plugin 중에서 `validate-auth-server-token` 만 제거하면 되는 것 맞을까요?

2023-03-15 01:56 UTC, boksil-lion requested changes
private ingress 에서 kongPlugin 연동하는 부분에, `_helpers.tpl`에서 지정한 값을 사용하는 것으로 개선하면 좋을 것 같습니다. 추가로, kongPlugin 이름의 변수명이 좀 혼란이 있어서 변경하면 어떨까 하는 의견 남겼습니다. 참고해주세요. 수정하지 않아도 기대한 동작을 하는 것에는 문제 없을 것 같습니다!

고생하셨어요!

2023-03-15 01:56 UTC, boksil-lion commented on charts/kkr/wallet-api/templates/ingress/ingress.api.public.yaml
> +    {{- toYaml . | nindent 4 }}
네, 맞습니다.

2023-03-15 01:56 UTC, boksil-lion commented on charts/kkr/wallet-api/templates/_helpers.tpl
> +{{- end }}
```suggestion
{{- define "wallet-api.corsPluginName" -}}
{{ $fullName := include "wallet-api.fullname" . }}
{{- printf "%s-%s" $fullName "cors" | trunc 63 }}
{{- end }}

{{/*
Create kongplugin name of validate auth server token
*/}}
{{- define "wallet-api.validateAuthServerTokenPluginName" -}}
{{ $fullName := include "wallet-api.fullname" . }}
{{- printf "%s-%s" $fullName "validate-auth-server-token" | trunc 63 }}
{{- end }}
```

이름만으로 kongPlugin 이라는 걸 알 수 있으면 더 좋을 것 같습니다.

2023-03-15 01:56 UTC, boksil-lion commented on charts/kkr/wallet-api/templates/ingress/ingress.api.private.yaml
> +    konghq.com/plugins: {{ $fullName }}-cors,{{ $fullName }}-validate-auth-server-token
`_helpers.tpl`에서 선언한 내용이 있으니, 이 곳에서도 그 값을 사용하는게 좋을 것 같네요.

```suggestion
    konghq.com/plugins: {{ include "wallet-api.cors" . }},{{ include "wallet-api. validateAuthServerToken" . }}
```

2023-03-15 01:56 UTC, boksil-lion commented on charts/kkr/wallet-api/templates/ingress/ingress.api.public.yaml
> +    konghq.com/plugins: {{ $fullName }}-cors
```suggestion
    konghq.com/plugins: {{ include "wallet-api.cors" . }}
```
`_helpers.tpl`에서 선언한 값을 사용하는 것이 더 좋을 것 같습니다.

2023-03-15 01:58 UTC, boksil-lion commented on charts/kkr/wallet-api/templates/ingress/ingress.api.public.yaml
> +    konghq.com/plugins: {{ $fullName }}-cors
기시감이 들어서 다시 확인해보니, #2 에 리뷰한 내용이네요!

2023-03-23 07:52 UTC, changpyo-modernlion commented on charts/kkr/wallet-api/templates/_helpers.tpl
> +{{- end }}
다른 chart에서도 사용하고 있어서 그대로 유지하고 일괄 수정하겠습니다.

2023-03-23 07:54 UTC, changpyo-modernlion commented on charts/kkr/wallet-api/templates/ingress/ingress.api.private.yaml
> +    konghq.com/plugins: {{ include "wallet-api.cors" . }},{{ include "wallet-api. validateAuthServerToken" . }}
```suggestion
    konghq.com/plugins: {{ include "wallet-api.cors" . }},{{ include "wallet-api.validateAuthServerToken" . }}
```

2023-03-23 07:58 UTC, changpyo-modernlion commented on charts/kkr/wallet-api/values.yaml
> +  enabled: true
```suggestion
  enabled: false
```

2023-03-23 08:04 UTC, changpyo-modernlion approved these changes
확인하였습니다.

2023-03-23 08:04 UTC, merged